import {execFileSync} from 'node:child_process';
import {mkdtemp,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
type Side='BUY'|'SELL'; type Agg={time:number;price:number;qty:number};
type Bar={time:number;open:number;high:number;low:number;close:number;volume:number};
type Mode=0|1|2;
type Cfg={mode:Mode,useLimit:boolean,limitOffset:number,expiryBars:number,slAtr:number,rr:number,adxMin:number,emaTrend:number};
type Stats={trades:number,winRate:number,pf:number,returnPct:number,ddPct:number,tradesPerDay:number,final50:number};
const SYMBOL='XAUUSDT',DAY=86400000,DAYS=84,EXPOSURE=.10;const BASE=`https://data.binance.vision/data/futures/um/daily/aggTrades/${SYMBOL}`;
function norm(v:number){if(v>1e17)return Math.floor(v/1e6);if(v>1e14)return Math.floor(v/1e3);return v}
async function fetchDay(d:string,dir:string){const fn=`${SYMBOL}-aggTrades-${d}.zip`,r=await fetch(`${BASE}/${fn}`);if(r.status===404)return[] as Agg[];if(!r.ok)throw Error(`VISION_${r.status}:${d}`);const f=path.join(dir,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));const csv=execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:512*1024*1024});const out:Agg[]=[];for(const line of csv.split(/\r?\n/)){if(!line.trim())continue;const c=line.split(','),p=+c[1],q=+c[2],t=+c[5];if(Number.isFinite(p)&&Number.isFinite(q)&&Number.isFinite(t))out.push({time:norm(t),price:p,qty:q})}return out}
function agg(rows:Agg[],ms:number){const m=new Map<number,Bar>();for(const x of rows){const k=Math.floor(x.time/ms)*ms;let b=m.get(k);if(!b){b={time:k,open:x.price,high:x.price,low:x.price,close:x.price,volume:0};m.set(k,b)}b.high=Math.max(b.high,x.price);b.low=Math.min(b.low,x.price);b.close=x.price;b.volume+=x.qty}return[...m.values()].sort((a,b)=>a.time-b.time)}
function ema(a:number[],p:number){const out=new Float64Array(a.length),k=2/(p+1);let x=a[0]||0;out[0]=x;for(let i=1;i<a.length;i++){x=a[i]*k+x*(1-k);out[i]=x}return out}
function atr(b:Bar[],p=14){const tr=new Float64Array(b.length),out=new Float64Array(b.length);for(let i=1;i<b.length;i++)tr[i]=Math.max(b[i].high-b[i].low,Math.abs(b[i].high-b[i-1].close),Math.abs(b[i].low-b[i-1].close));let s=0;for(let i=1;i<b.length;i++){if(i<=p){s+=tr[i];out[i]=s/i}else out[i]=(out[i-1]*(p-1)+tr[i])/p}return out}
function adx(b:Bar[],p=14){const n=b.length,tr=new Float64Array(n),pd=new Float64Array(n),md=new Float64Array(n),pdi=new Float64Array(n),mdi=new Float64Array(n),dx=new Float64Array(n),adx=new Float64Array(n);for(let i=1;i<n;i++){const up=b[i].high-b[i-1].high,dn=b[i-1].low-b[i].low;pd[i]=up>dn&&up>0?up:0;md[i]=dn>up&&dn>0?dn:0;tr[i]=Math.max(b[i].high-b[i].low,Math.abs(b[i].high-b[i-1].close),Math.abs(b[i].low-b[i-1].close))}let st=0,sp=0,sm=0;for(let i=1;i<n;i++){if(i<=p){st+=tr[i];sp+=pd[i];sm+=md[i]}else{st=st-st/p+tr[i];sp=sp-sp/p+pd[i];sm=sm-sm/p+md[i]}if(i>=p){pdi[i]=st?100*sp/st:0;mdi[i]=st?100*sm/st:0;const den=pdi[i]+mdi[i];dx[i]=den?100*Math.abs(pdi[i]-mdi[i])/den:0}}let sx=0;for(let i=p;i<n;i++){if(i<2*p){sx+=dx[i];if(i===2*p-1)adx[i]=sx/p}else adx[i]=(adx[i-1]*(p-1)+dx[i])/p}return{adx,pdi,mdi}}
function prep(b:Bar[],trendPeriods:number[]){const c=b.map(x=>x.close),atr14=atr(b,14),d=adx(b,14),e8=ema(c,8),e14=ema(c,14),trend=new Map<number,Float64Array>();for(const p of trendPeriods)trend.set(p,ema(c,p));return{atr14,...d,e8,e14,trend}}
function run(b:Bar[],P:ReturnType<typeof prep>,cfg:Cfg,start:number,end:number):Stats{let eq=100,pk=100,dd=0,gp=0,gl=0,w=0,n=0,i=Math.max(start,cfg.emaTrend+20);const et=P.trend.get(cfg.emaTrend)!;while(i<Math.min(end-2,b.length-2)){const close=b[i].close,A=P.atr14[i];if(!(A>0)||P.adx[i]<cfg.adxMin){i++;continue}const up=close>et[i]&&P.e8[i]>P.e14[i]&&P.pdi[i]>P.mdi[i],dn=close<et[i]&&P.e8[i]<P.e14[i]&&P.mdi[i]>P.pdi[i];const top=Math.max(P.e8[i],P.e14[i]),bot=Math.min(P.e8[i],P.e14[i]);const pullB=b[i].low<=top+A*.20&&close>top&&close>b[i].open,pullS=b[i].high>=bot-A*.20&&close<bot&&close<b[i].open;const breakB=close>Math.max(b[i-1].high,b[i-2].high)&&close>b[i].open,breakS=close<Math.min(b[i-1].low,b[i-2].low)&&close<b[i].open;let side:Side|null=null;if(up&&((cfg.mode===0&&pullB)||(cfg.mode===1&&breakB)||(cfg.mode===2&&(pullB||breakB))))side='BUY';if(dn&&((cfg.mode===0&&pullS)||(cfg.mode===1&&breakS)||(cfg.mode===2&&(pullS||breakS))))side='SELL';if(!side){i++;continue}
let entry=0,fill=-1;if(cfg.useLimit){entry=side==='BUY'?close-A*cfg.limitOffset:close+A*cfg.limitOffset;for(let j=i+1;j<=Math.min(i+cfg.expiryBars,end-1);j++){if(side==='BUY'?b[j].low<=entry:b[j].high>=entry){fill=j;break}}if(fill<0){i+=cfg.expiryBars+1;continue}}else{fill=i+1;entry=b[fill].open}
const slD=A*cfg.slAtr,tpD=slD*cfg.rr,sl=side==='BUY'?entry-slD:entry+slD,tp=side==='BUY'?entry+tpD:entry-tpD;let exit=b[Math.min(end-1,fill+72)].close,xi=Math.min(end-1,fill+72);for(let j=fill;j<Math.min(end,fill+73);j++){const hitSl=side==='BUY'?b[j].low<=sl:b[j].high>=sl,hitTp=side==='BUY'?b[j].high>=tp:b[j].low<=tp;if(hitSl){exit=sl;xi=j;break}if(hitTp){exit=tp;xi=j;break}}
const gross=(side==='BUY'?exit/entry-1:entry/exit-1)*100;const cost=cfg.useLimit?.10:.145,net=gross-cost,ar=net*EXPOSURE;eq*=1+ar/100;pk=Math.max(pk,eq);dd=Math.max(dd,(pk-eq)/pk*100);n++;if(ar>0){w++;gp+=ar}else gl+=Math.abs(ar);i=xi+1}
const days=Math.max(1,(b[Math.min(end-1,b.length-1)].time-b[Math.max(start,0)].time)/DAY);return{trades:n,winRate:n?w/n*100:0,pf:gl?gp/gl:gp?99:0,returnPct:eq-100,ddPct:dd,tradesPerDay:n/days,final50:eq/2}}
function score(s:Stats){if(s.trades<20)return-999;return s.returnPct-s.ddPct*.45+(s.pf-1)*3+Math.min(2,s.tradesPerDay*.12)}
async function main(){const end=Math.floor((Date.now()-2*DAY)/DAY)*DAY,start=end-DAYS*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'r23-'));let b:Bar[]=[];for(let t=start;t<end;t+=DAY){const d=new Date(t).toISOString().slice(0,10),r=await fetchDay(d,dir),a=agg(r,600000);console.log('DAY',d,r.length,a.length);b.push(...a)}b.sort((a,z)=>a.time-z.time);console.log('BARS',b.length);const periods=[100,150,200],P=prep(b,periods),N=b.length,t1=Math.floor(N*.5),t2=Math.floor(N*.75);
const base:Cfg={mode:2,useLimit:true,limitOffset:.20,expiryBars:3,slAtr:.95,rr:1.5,adxMin:18,emaTrend:150};const baseRes={train:run(b,P,base,0,t1),validation:run(b,P,base,t1,t2),test:run(b,P,base,t2,N)};console.log('R23_BASE',JSON.stringify(baseRes));
const cfgs:Cfg[]=[];for(const mode of [0,1,2] as Mode[])for(const useLimit of [true,false])for(const limitOffset of (useLimit?[.10,.20,.30]:[0]))for(const expiryBars of (useLimit?[1,2,3]:[1]))for(const slAtr of [.70,.95,1.20,1.50])for(const rr of [1.0,1.5,2.0,2.5])for(const adxMin of [14,18,22,26])for(const emaTrend of periods)cfgs.push({mode,useLimit,limitOffset,expiryBars,slAtr,rr,adxMin,emaTrend});console.log('CONFIGS',cfgs.length);
const rows=cfgs.map(c=>{const tr=run(b,P,c,0,t1),va=run(b,P,c,t1,t2);return{c,tr,va,s:score(tr)+score(va)*1.6}}).sort((a,z)=>z.s-a.s);console.log('R23_TOP10',JSON.stringify(rows.slice(0,10)));const best=rows[0],test=run(b,P,best.c,t2,N);console.log('R23_RESULT',JSON.stringify({symbol:SYMBOL,days:DAYS,barsM10:N,proxy:'XAUUSDT Binance futures used as XAU M10 proxy',costPct:{limitRoundTrip:.10,marketRoundTrip:.145},risk:{initial:50,normalizedExposurePct:10},base:{config:base,...baseRes},optimized:{config:best.c,train:best.tr,validation:best.va,test,survived:best.tr.returnPct>0&&best.va.returnPct>0&&test.returnPct>0&&best.va.pf>1&&test.pf>1}}))}
main().catch(e=>{console.error('R23_ERROR',e);process.exit(1)});
