import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { evaluateConsensus100R18 } from './consensus100R18.js';
import type { CommodityCandleR15, CommodityMicroBarR15 } from './commodityStrategyR15.js';

interface Agg { time:number; price:number; qty:number; buyerIsMaker:boolean }
interface Stats { trades:number; wins:number; losses:number; winRate:number; profitFactor:number; returnPct:number; maxDrawdownPct:number; expectancyPct:number; tradesPerDay:number; final50:number; avgBuyVotes:number; avgSellVotes:number }
const SYMBOL='XAUUSDT', DAY=86_400_000, DAYS=14, SPREAD_PCT=0.025, FEE_PCT=0.05, SLIPPAGE_PCT=0.01, LEVERAGE=10, MARGIN_PCT=1;
const BASE=`https://data.binance.vision/data/futures/um/daily/aggTrades/${SYMBOL}`;
function norm(v:number){if(v>1e17)return Math.floor(v/1_000_000);if(v>1e14)return Math.floor(v/1000);return v;}
async function fetchDay(day:string,dir:string):Promise<Agg[]>{const fn=`${SYMBOL}-aggTrades-${day}.zip`,r=await fetch(`${BASE}/${fn}`);if(r.status===404)return[];if(!r.ok)throw new Error(`VISION_${r.status}:${day}`);const f=path.join(dir,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));const csv=execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:512*1024*1024});const out:Agg[]=[];for(const line of csv.split(/\r?\n/)){if(!line.trim())continue;const c=line.split(','),p=+c[1],q=+c[2],t=norm(+c[5]);if(Number.isFinite(p)&&Number.isFinite(q)&&Number.isFinite(t))out.push({time:t,price:p,qty:q,buyerIsMaker:String(c[6]).trim().toLowerCase()==='true'});}return out;}
function micro(rows:Agg[]):CommodityMicroBarR15[]{const m=new Map<number,CommodityMicroBarR15>();for(const x of rows){const k=Math.floor(x.time/30_000)*30_000;let b=m.get(k);if(!b){b={time:k,open:x.price,high:x.price,low:x.price,close:x.price,volume:0,buyVolume:0,sellVolume:0};m.set(k,b);}b.high=Math.max(b.high,x.price);b.low=Math.min(b.low,x.price);b.close=x.price;b.volume+=x.qty;if(x.buyerIsMaker)b.sellVolume+=x.qty;else b.buyVolume+=x.qty;}return[...m.values()].sort((a,b)=>a.time-b.time);}
function toM1(src:CommodityMicroBarR15[]):CommodityCandleR15[]{const m=new Map<number,CommodityCandleR15>();for(const x of src){const k=Math.floor(x.time/60_000)*60_000;let b=m.get(k);if(!b){b={time:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:0};m.set(k,b);}b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=x.volume;}return[...m.values()].sort((a,b)=>a.time-b.time);}
function run(bars:CommodityMicroBarR15[],start:number,end:number):Stats{let equity=100,peak=100,dd=0,gp=0,gl=0,w=0,l=0,n=0,sum=0,bv=0,sv=0;for(let i=Math.max(start,120);i<Math.min(end-20,bars.length-20);){const hist=bars.slice(Math.max(0,i-119),i+1),m1All=toM1(bars.slice(Math.max(0,i-359),i+1)),mid=bars[i].close,bid=mid*(1-SPREAD_PCT/200),ask=mid*(1+SPREAD_PCT/200);const d=evaluateConsensus100R18({kind:'XAU',allowLong:true,allowShort:true,maxSpreadPct:0.05,feePct:FEE_PCT,slippagePct:SLIPPAGE_PCT,minVotes:5,minFamilies:3,minVoteLead:2},{bid,ask,time:bars[i].time},m1All,hist);bv+=d.buyVotes;sv+=d.sellVotes;if(!d.signal){i++;continue;}const s=d.signal;let exit=bars[Math.min(end-1,i+20)].close,xi=Math.min(end-1,i+20),reason='TIME';for(let j=i+1;j<=Math.min(end-1,i+20);j++){const x=bars[j],hitSl=s.side==='BUY'?x.low<=s.stopLoss:x.high>=s.stopLoss,hitTp=s.side==='BUY'?x.high>=s.takeProfit:x.low<=s.takeProfit;if(hitSl){exit=s.stopLoss;xi=j;reason='SL';break;}if(hitTp){exit=s.takeProfit;xi=j;reason='TP';break;}}const grossPct=s.side==='BUY'?(exit/s.entry-1)*100:(s.entry/exit-1)*100;const accountPct=(grossPct-d.costPct)*(LEVERAGE*MARGIN_PCT/100);equity*=1+accountPct/100;peak=Math.max(peak,equity);dd=Math.max(dd,(peak-equity)/peak*100);sum+=accountPct;n++;if(accountPct>0){w++;gp+=accountPct}else{l++;gl+=Math.abs(accountPct)};if(n<=5)console.log('SAMPLE_TRADE',JSON.stringify({time:new Date(bars[i].time).toISOString(),side:s.side,buyVotes:d.buyVotes,sellVotes:d.sellVotes,families:d.winningFamilies,targetPct:d.targetPct,stopPct:d.stopPct,result:reason,accountPct}));i=xi+1;}const days=Math.max(1,(bars[Math.max(start+1,Math.min(end-1,bars.length-1))].time-bars[Math.max(0,start)].time)/DAY);return{trades:n,wins:w,losses:l,winRate:n?w/n*100:0,profitFactor:gl?gp/gl:gp?99:0,returnPct:equity-100,maxDrawdownPct:dd,expectancyPct:n?sum/n:0,tradesPerDay:n/days,final50:50*equity/100,avgBuyVotes:(end-start)?bv/(end-start):0,avgSellVotes:(end-start)?sv/(end-start):0};}
async function main(){const end=Math.floor((Date.now()-2*DAY)/DAY)*DAY,start=end-DAYS*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'r18-'));const bars:CommodityMicroBarR15[]=[];for(let t=start;t<end;t+=DAY){const d=new Date(t).toISOString().slice(0,10),rows=await fetchDay(d,dir),b=micro(rows);console.log('DAY',d,'aggTrades',rows.length,'bars30s',b.length);bars.push(...b);}bars.sort((a,b)=>a.time-b.time);const n=bars.length,a=Math.floor(n*.5),b=Math.floor(n*.75),train=run(bars,0,a),validation=run(bars,a,b),test=run(bars,b,n),survived=train.trades>=20&&validation.trades>=8&&test.trades>=8&&train.returnPct>0&&validation.returnPct>0&&test.returnPct>0&&train.profitFactor>1&&validation.profitFactor>1&&test.profitFactor>1;console.log('R18_CONSENSUS_BACKTEST',JSON.stringify({symbol:SYMBOL,days:DAYS,bars30s:n,strategies:100,minVotes:5,minFamilies:3,minVoteLead:2,costModel:{spreadPct:SPREAD_PCT,feePctPerSide:FEE_PCT,slippagePctPerSide:SLIPPAGE_PCT},risk:{initial:50,marginPct:MARGIN_PCT,leverage:LEVERAGE},train,validation,test,survived}));}
main().catch(e=>{console.error('R18_BACKTEST_ERROR',e instanceof Error?e.message:String(e));process.exit(1);});
