import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { evaluateConsensus100R18 } from './consensus100R18.js';
import type { CommodityCandleR15, CommodityMicroBarR15 } from './commodityStrategyR15.js';

type Agg={time:number;price:number;qty:number;buyerIsMaker:boolean};
type Snap={i:number;buyVotes:number;sellVotes:number;buyFamilies:number;sellFamilies:number;targetPct:number;stopPct:number;costPct:number;bid:number;ask:number};
type Stats={trades:number;winRate:number;pf:number;returnPct:number;ddPct:number;tradesPerDay:number;final50:number};
const SYMBOL='XAUUSDT',DAY=86400000,DAYS=14,SPREAD=.025,FEE=.05,SLIP=.01,EXPOSURE=.10,BASE=`https://data.binance.vision/data/futures/um/daily/aggTrades/${SYMBOL}`;
function norm(v:number){if(v>1e17)return Math.floor(v/1e6);if(v>1e14)return Math.floor(v/1000);return v;}
async function fd(d:string,dir:string){const fn=`${SYMBOL}-aggTrades-${d}.zip`,r=await fetch(`${BASE}/${fn}`);if(r.status===404)return[] as Agg[];if(!r.ok)throw new Error(`VISION_${r.status}:${d}`);const f=path.join(dir,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));const csv=execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:512*1024*1024}),o:Agg[]=[];for(const l of csv.split(/\r?\n/)){if(!l.trim())continue;const c=l.split(','),p=+c[1],q=+c[2],t=norm(+c[5]);if(Number.isFinite(p)&&Number.isFinite(q)&&Number.isFinite(t))o.push({time:t,price:p,qty:q,buyerIsMaker:String(c[6]).trim().toLowerCase()==='true'});}return o;}
function micro(a:Agg[]):CommodityMicroBarR15[]{const m=new Map<number,CommodityMicroBarR15>();for(const x of a){const k=Math.floor(x.time/30000)*30000;let b=m.get(k);if(!b){b={time:k,open:x.price,high:x.price,low:x.price,close:x.price,volume:0,buyVolume:0,sellVolume:0};m.set(k,b);}b.high=Math.max(b.high,x.price);b.low=Math.min(b.low,x.price);b.close=x.price;b.volume+=x.qty;if(x.buyerIsMaker)b.sellVolume+=x.qty;else b.buyVolume+=x.qty;}return[...m.values()].sort((a,b)=>a.time-b.time);}
function m1(a:CommodityMicroBarR15[]):CommodityCandleR15[]{const m=new Map<number,CommodityCandleR15>();for(const x of a){const k=Math.floor(x.time/60000)*60000;let b=m.get(k);if(!b){b={time:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:0};m.set(k,b);}b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=x.volume;}return[...m.values()].sort((a,b)=>a.time-b.time);}
function sim(bars:CommodityMicroBarR15[],snaps:Snap[],from:number,to:number,mv:number,mf:number):Stats{let eq=100,pk=100,dd=0,gp=0,gl=0,w=0,n=0;const map=new Map(snaps.map(s=>[s.i,s]));for(let i=Math.max(from,120);i<Math.min(to-20,bars.length-20);){const s=map.get(i);if(!s){i++;continue;}let side:'BUY'|'SELL'|null=null;const bOk=s.buyVotes>=mv&&s.buyFamilies>=mf&&s.buyVotes>=s.sellVotes+2,slOk=s.sellVotes>=mv&&s.sellFamilies>=mf&&s.sellVotes>=s.buyVotes+2;if(bOk)side='BUY';else if(slOk)side='SELL';if(!side){i++;continue;}const entry=side==='BUY'?s.ask*(1+SLIP/100):s.bid*(1-SLIP/100),stop=side==='BUY'?entry*(1-s.stopPct/100):entry*(1+s.stopPct/100),tp=side==='BUY'?entry*(1+s.targetPct/100):entry*(1-s.targetPct/100);let exit=bars[i+20].close,xi=i+20;for(let j=i+1;j<=i+20;j++){const x=bars[j],hs=side==='BUY'?x.low<=stop:x.high>=stop,ht=side==='BUY'?x.high>=tp:x.low<=tp;if(hs){exit=stop;xi=j;break;}if(ht){exit=tp;xi=j;break;}}const gross=side==='BUY'?(exit/entry-1)*100:(entry/exit-1)*100,ar=(gross-s.costPct)*EXPOSURE;eq*=1+ar/100;pk=Math.max(pk,eq);dd=Math.max(dd,(pk-eq)/pk*100);n++;if(ar>0){w++;gp+=ar}else gl+=Math.abs(ar);i=xi+1;}const days=Math.max(1,(bars[Math.max(from+1,Math.min(to-1,bars.length-1))].time-bars[Math.max(0,from)].time)/DAY);return{trades:n,winRate:n?w/n*100:0,pf:gl?gp/gl:gp?99:0,returnPct:eq-100,ddPct:dd,tradesPerDay:n/days,final50:50*eq/100};}
async function main(){const end=Math.floor((Date.now()-2*DAY)/DAY)*DAY,start=end-DAYS*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'r18s-')),bars:CommodityMicroBarR15[]=[];for(let t=start;t<end;t+=DAY){const d=new Date(t).toISOString().slice(0,10),r=await fd(d,dir),b=micro(r);console.log('DAY',d,r.length,b.length);bars.push(...b);}bars.sort((a,b)=>a.time-b.time);const snaps:Snap[]=[];for(let i=120;i<bars.length-20;i++){const hist=bars.slice(i-119,i+1),mm=m1(bars.slice(Math.max(0,i-359),i+1)),mid=bars[i].close,bid=mid*(1-SPREAD/200),ask=mid*(1+SPREAD/200),d=evaluateConsensus100R18({kind:'XAU',allowLong:true,allowShort:true,maxSpreadPct:.05,feePct:FEE,slippagePct:SLIP,minVotes:5,minFamilies:1,minVoteLead:0},{bid,ask,time:bars[i].time},mm,hist);snaps.push({i,buyVotes:d.buyVotes,sellVotes:d.sellVotes,buyFamilies:d.buyFamilies,sellFamilies:d.sellFamilies,targetPct:d.targetPct,stopPct:d.stopPct,costPct:d.costPct,bid,ask});}const n=bars.length,a=Math.floor(n*.5),b=Math.floor(n*.75),rows:any[]=[];for(const mv of [5,10,15,20,25,30,40,50])for(const mf of [3,4,5,6,7]){const tr=sim(bars,snaps,0,a,mv,mf),va=sim(bars,snaps,a,b,mv,mf),te=sim(bars,snaps,b,n,mv,mf),surv=tr.trades>=15&&va.trades>=5&&te.trades>=5&&tr.returnPct>0&&va.returnPct>0&&te.returnPct>0&&tr.pf>1&&va.pf>1&&te.pf>1;rows.push({minVotes:mv,minFamilies:mf,train:tr,validation:va,test:te,survived:surv});}rows.sort((x,y)=>(Number(y.survived)-Number(x.survived))||(y.test.returnPct-x.test.returnPct));console.log('R18_SWEEP_TOP',JSON.stringify(rows.slice(0,12)));console.log('R18_SWEEP_SURVIVORS',JSON.stringify(rows.filter(x=>x.survived)));}
main().catch(e=>{console.error('R18_SWEEP_ERROR',e instanceof Error?e.message:String(e));process.exit(1);});
