import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { Candle } from './analysis.js';

const DAY=86_400_000,MIN=60_000,M15=15*MIN,H4=4*60*MIN;
const VISION='https://data.binance.vision/data/futures/um/monthly/klines';
const INITIAL=50,LEVERAGE=10,MARGIN_PCT=1;
const BASE={fee:.05,spread:.025,slip:.01,funding8h:.005};
interface P{lookback:number;threshold:number;hold:number;vol:number;}
interface F extends Candle{atrPct:number;h4e20:number;h4e50:number;}
interface Trade{time:number;side:'BUY'|'SELL';returnPct:number;pnl:number;heldHours:number;}
interface M{trades:number;wins:number;winRate:number;pf:number;returnPct:number;dd:number;balance:number;expectancy:number;buyTrades:number;sellTrades:number;}
const MODEL:P={lookback:64,threshold:1,hold:64,vol:1};

async function main(){const endDay=Math.floor((Date.now()-DAY)/DAY)*DAY,end=endDay+DAY-1,start=end-240*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'r15-survivor-')),m1=await fetchVision('XAUUSDT',start,end,dir),m15=aggregate(m1,M15),h4=aggregate(m1,H4),f=features(m15,h4);if(f.length<10000)throw new Error(`SURVIVOR_HISTORY_SHORT:${f.length}`);const first=f[0].time,last=f.at(-1)!.time;
const base=simulate(f,500,f.length-2,MODEL,1);console.log('R15_SURVIVOR_BASE',JSON.stringify({model:MODEL,from:new Date(first).toISOString(),to:new Date(last).toISOString(),metrics:c(base.m),tradeSample:base.trades.length,cost:BASE}));
for(const mult of [1,1.25,1.5,2]){const r=simulate(f,500,f.length-2,MODEL,mult);console.log('R15_SURVIVOR_COST_STRESS',JSON.stringify({costMultiplier:mult,metrics:c(r.m)}));}
const windows=[] as any[];for(let s=first;s<last;s+=30*DAY){const e=Math.min(last,s+30*DAY),i0=Math.max(500,lowerBound(f,s)),i1=Math.min(f.length-2,lowerBound(f,e)-1);if(i1<=i0)continue;const r=simulate(f,i0,i1,MODEL,1);windows.push({from:new Date(s).toISOString().slice(0,10),to:new Date(e).toISOString().slice(0,10),...c(r.m)});}console.log('R15_SURVIVOR_ROLLING',JSON.stringify({windows,positiveWindows:windows.filter(x=>x.returnPct>0).length,totalWindows:windows.length}));
const split=Math.floor(f.length*.75),neighborhood=[] as any[];for(const lookback of [56,64,72])for(const threshold of [.8,1,1.2])for(const hold of [56,64,72])for(const vol of [.9,1,1.1]){const p={lookback,threshold,hold,vol},full=simulate(f,500,f.length-2,p,1).m,test=simulate(f,Math.max(500,split),f.length-2,p,1).m;neighborhood.push({p,full:c(full),test:c(test)});}const positiveTest=neighborhood.filter(x=>x.test.trades>=10&&x.test.returnPct>0&&x.test.pf>1).length,positiveFull=neighborhood.filter(x=>x.full.returnPct>0&&x.full.pf>1).length;console.log('R15_SURVIVOR_SENSITIVITY',JSON.stringify({variants:neighborhood.length,positiveFull,positiveTest,positiveFullPct:Number((positiveFull/neighborhood.length*100).toFixed(1)),positiveTestPct:Number((positiveTest/neighborhood.length*100).toFixed(1)),baseNeighbor:neighborhood.find(x=>x.p.lookback===64&&x.p.threshold===1&&x.p.hold===64&&x.p.vol===1)}));
const mc=monteCarlo(base.trades.map(t=>t.returnPct),10000);console.log('R15_SURVIVOR_MONTE_CARLO',JSON.stringify(mc));
const buy=base.trades.filter(t=>t.side==='BUY'),sell=base.trades.filter(t=>t.side==='SELL');console.log('R15_SURVIVOR_SIDE',JSON.stringify({buy:tradeStats(buy),sell:tradeStats(sell)}));
const pass=base.m.returnPct>0&&base.m.pf>=1.1&&simulate(f,500,f.length-2,MODEL,1.5).m.returnPct>=0&&positiveTest/neighborhood.length>=.5&&mc.lossProbabilityPct<35;console.log(pass?'R15_SURVIVOR_ROBUST_PASS':'R15_SURVIVOR_ROBUST_FAIL',JSON.stringify({pass}));}

function simulate(f:F[],start:number,end:number,p:P,costMult:number){let bal=INITIAL,peak=INITIAL,dd=0,w=0,gp=0,gl=0,n=0,buy=0,sell=0,i=Math.max(start,Math.max(500,p.lookback+5));const trades:Trade[]=[];while(i<end-2&&bal>1){const b=f[i],avgAtr=mean(f.slice(Math.max(0,i-100),i).map(x=>x.atrPct));if(!(avgAtr>0)||b.atrPct<avgAtr*p.vol||i<p.lookback){i++;continue;}const mom=(b.close-f[i-p.lookback].close)/f[i-p.lookback].close*100;if(Math.abs(mom)<p.threshold){i++;continue;}const side:mom extends never?never:1|-1=mom>0?1:-1;const regime=side===1?b.h4e20>=b.h4e50:b.h4e20<=b.h4e50;if(!regime){i++;continue;}const e=i+1,entry=f[e].open*(1+side*(BASE.spread/2+BASE.slip)*costMult/100),x=Math.min(end,e+p.hold),exitRaw=f[x].close,exit=exitRaw*(1-side*(BASE.spread/2+BASE.slip)*costMult/100),notional=bal*MARGIN_PCT/100*LEVERAGE,qty=notional/entry,fees=(notional+qty*exit)*BASE.fee*costMult/100,held=(x-e+1)*.25,funding=notional*BASE.funding8h*costMult/100*Math.floor(held/8),gross=side===1?(exit-entry)*qty:(entry-exit)*qty,pnl=gross-fees-funding,before=bal;bal+=pnl;n++;if(side===1)buy++;else sell++;if(pnl>0){w++;gp+=pnl}else gl+=Math.abs(pnl);peak=Math.max(peak,bal);dd=Math.max(dd,(peak-bal)/peak*100);trades.push({time:f[e].time,side:side===1?'BUY':'SELL',returnPct:before>0?pnl/before*100:0,pnl,heldHours:held});i=Math.max(i+1,x+1);}return{m:{trades:n,wins:w,winRate:n?w/n*100:0,pf:gl>0?gp/gl:gp>0?99:0,returnPct:(bal-INITIAL)/INITIAL*100,dd,balance:bal,expectancy:n?(bal-INITIAL)/n:0,buyTrades:buy,sellTrades:sell} as M,trades};}
function monteCarlo(r:number[],runs:number){if(!r.length)return{runs:0};const finals:number[]=[],dds:number[]=[];let losses=0;const rnd=lcg(340015);for(let k=0;k<runs;k++){let eq=INITIAL,peak=INITIAL,dd=0;for(let i=0;i<r.length;i++){const x=r[Math.floor(rnd()*r.length)];eq*=1+x/100;peak=Math.max(peak,eq);dd=Math.max(dd,(peak-eq)/peak*100);}finals.push((eq-INITIAL)/INITIAL*100);dds.push(dd);if(eq<INITIAL)losses++;}finals.sort((a,b)=>a-b);dds.sort((a,b)=>a-b);return{runs,tradesPerRun:r.length,lossProbabilityPct:Number((losses/runs*100).toFixed(2)),returnP05:Number(q(finals,.05).toFixed(3)),returnMedian:Number(q(finals,.5).toFixed(3)),returnP95:Number(q(finals,.95).toFixed(3)),maxDdP50:Number(q(dds,.5).toFixed(3)),maxDdP95:Number(q(dds,.95).toFixed(3))};}
function tradeStats(t:Trade[]){const gains=t.filter(x=>x.pnl>0).reduce((s,x)=>s+x.pnl,0),loss=t.filter(x=>x.pnl<=0).reduce((s,x)=>s+Math.abs(x.pnl),0);return{trades:t.length,winRate:t.length?Number((t.filter(x=>x.pnl>0).length/t.length*100).toFixed(2)):0,pf:loss?Number((gains/loss).toFixed(3)):gains?99:0,meanReturnPct:Number(mean(t.map(x=>x.returnPct)).toFixed(4))};}
function c(m:M){return{trades:m.trades,winRate:Number(m.winRate.toFixed(2)),pf:Number(m.pf.toFixed(3)),returnPct:Number(m.returnPct.toFixed(3)),dd:Number(m.dd.toFixed(3)),balance:Number(m.balance.toFixed(4)),expectancy:Number(m.expectancy.toFixed(5)),buyTrades:m.buyTrades,sellTrades:m.sellTrades}}
function features(m15:Candle[],h4:Candle[]):F[]{const a=atr(m15,14),h=h4.map(x=>x.close),e20=ema(h,20),e50=ema(h,50);let j=0;return m15.map((x,i)=>{const close=x.time+M15;while(j+1<h4.length&&h4[j+1].time+H4<=close)j++;return{...x,atrPct:x.close>0?a[i]/x.close*100:0,h4e20:e20[j]??0,h4e50:e50[j]??0};});}
function lowerBound(a:F[],t:number){let l=0,r=a.length;while(l<r){const m=(l+r)>>1;if(a[m].time<t)l=m+1;else r=m;}return l}function q(a:number[],p:number){return a[Math.min(a.length-1,Math.max(0,Math.floor((a.length-1)*p)))]??0}function lcg(seed:number){let x=seed>>>0;return()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296}}
function aggregate(rows:Candle[],bucket:number){const map=new Map<number,Candle>();for(const x of rows){const t=Math.floor(x.time/bucket)*bucket,b=map.get(t);if(!b)map.set(t,{...x,time:t});else{b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=x.volume;}}return[...map.values()].sort((a,b)=>a.time-b.time)}function ema(v:number[],p:number){const o=new Array(v.length).fill(0);if(!v.length)return o;const k=2/(p+1);o[0]=v[0];for(let i=1;i<v.length;i++)o[i]=v[i]*k+o[i-1]*(1-k);return o}function atr(r:Candle[],p:number){const o=new Array(r.length).fill(0);if(!r.length)return o;o[0]=r[0].high-r[0].low;for(let i=1;i<r.length;i++){const tr=Math.max(r[i].high-r[i].low,Math.abs(r[i].high-r[i-1].close),Math.abs(r[i].low-r[i-1].close));o[i]=i<p?(o[i-1]*i+tr)/(i+1):(o[i-1]*(p-1)+tr)/p;}return o}function mean(v:number[]){return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}
function monthKeys(start:number,end:number){const o:string[]=[];let d=new Date(Date.UTC(new Date(start).getUTCFullYear(),new Date(start).getUTCMonth(),1)),z=new Date(Date.UTC(new Date(end).getUTCFullYear(),new Date(end).getUTCMonth(),1));while(d<=z){o.push(`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`);d=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1));}return o;}async function fetchVision(symbol:string,start:number,end:number,dir:string):Promise<Candle[]>{const out:Candle[]=[];for(const month of monthKeys(start,end)){const fn=`${symbol}-1m-${month}.zip`,res=await fetch(`${VISION}/${symbol}/1m/${fn}`);if(res.status===404)continue;if(!res.ok)throw new Error(`VISION_${res.status}:${fn}`);const file=path.join(dir,fn);await writeFile(file,Buffer.from(await res.arrayBuffer()));const csv=execFileSync('unzip',['-p',file],{encoding:'utf8',maxBuffer:256*1024*1024});for(const line of csv.split(/\r?\n/)){if(!line.trim())continue;const a=line.split(','),raw=Number(a[0]);if(!Number.isFinite(raw))continue;const time=raw>1e17?Math.floor(raw/1_000_000):raw>1e14?Math.floor(raw/1000):raw,x:Candle={time,open:Number(a[1]),high:Number(a[2]),low:Number(a[3]),close:Number(a[4]),volume:Number(a[5]??0)};if([x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)&&time>=start&&time<=end)out.push(x)}}const map=new Map(out.map(x=>[x.time,x]));return[...map.values()].sort((a,b)=>a.time-b.time)}
main().catch(e=>{console.error('R15_SURVIVOR_ERROR',e instanceof Error?e.message:String(e));process.exit(1)});
