import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { Candle } from './analysis.js';

const DAY=86_400_000,MIN=60_000,M15=15*MIN,H1=60*MIN,H4=4*H1;
const VISION='https://data.binance.vision/data/futures/um/monthly/klines';
const LOOKBACK_DAYS=240,INITIAL=50,LEVERAGE=10,MARGIN_PCT=1;
const FEE_PCT=0.05,SPREAD_PCT=0.025,SLIP_PCT=0.01,FUNDING_ALLOWANCE_8H_PCT=0.005;
type Side=1|-1;
type Family='TSMOM'|'DUAL_TREND'|'DONCHIAN'|'VOL_BREAKOUT'|'PULLBACK_4H';
interface P{family:Family;lookback:number;threshold:number;stopAtr:number;rr:number;holdBars:number;volFilter:number;sideMode:'BOTH'|'BUY';}
interface F extends Candle{atr:number;atrPct:number;ema20:number;ema50:number;ema200:number;rsi:number;volAvg:number;h1e20:number;h1e50:number;h1e200:number;h1atr:number;h4e20:number;h4e50:number;h4e200:number;h4atr:number;h4slope:number;}
interface M{trades:number;wins:number;winRate:number;pf:number;returnPct:number;dd:number;balance:number;expectancy:number;avgHours:number;}
interface C{p:P;train:M;validation:M;test?:M;score:number;}

async function main(){const endDay=Math.floor((Date.now()-DAY)/DAY)*DAY,end=endDay+DAY-1,start=end-LOOKBACK_DAYS*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'r15-swing-'));const m1=await fetchVision('XAUUSDT',start,end,dir);if(m1.length<120*1440)throw new Error(`SWING_HISTORY_SHORT:${m1.length}`);const m15=aggregate(m1,M15),h1=aggregate(m1,H1),h4=aggregate(m1,H4),f=features(m15,h1,h4);const first=f[0].time,last=f.at(-1)!.time,span=last-first,s1=first+span*.5,s2=first+span*.75,i1=f.findIndex(x=>x.time>=s1),i2=f.findIndex(x=>x.time>=s2),endIdx=f.length-2,grid=buildGrid(),trained:C[]=[];
for(const p of grid){const train=sim(f,500,i1-1,p);if(train.trades<8||train.returnPct<=0||train.pf<1.05||train.dd>15)continue;const validation=sim(f,i1,i2-1,p),score=train.returnPct-train.dd*.7+Math.min(train.pf,3)*3+Math.min(train.trades,100)*.01;trained.push({p,train,validation,score});}trained.sort((a,b)=>b.score-a.score);const validated=trained.filter(x=>x.validation.trades>=4&&x.validation.returnPct>=0&&x.validation.pf>=1&&x.validation.dd<=12).slice(0,60).map(x=>({...x,test:sim(f,i2,endIdx,x.p)}));const survivors=validated.filter(x=>x.test&&x.test.trades>=4&&x.test.returnPct>0&&x.test.pf>=1.05&&x.test.dd<=12).sort((a,b)=>survival(b)-survival(a));console.log('R15_SWING_META',JSON.stringify({m1:m1.length,m15:m15.length,h1:h1.length,h4:h4.length,from:new Date(first).toISOString(),to:new Date(last).toISOString(),days:Number((span/DAY).toFixed(2)),grid:grid.length,positiveTrain:trained.length,validationPass:validated.length,survivors:survivors.length,cost:{feePct:FEE_PCT,spreadPct:SPREAD_PCT,slippagePct:SLIP_PCT,fundingAllowance8hPct:FUNDING_ALLOWANCE_8H_PCT,leverage:LEVERAGE,marginPct:MARGIN_PCT}}));for(const[i,x]of trained.slice(0,15).entries())console.log('R15_SWING_TRAIN',JSON.stringify({rank:i+1,p:x.p,train:c(x.train),validation:c(x.validation)}));for(const[i,x]of survivors.slice(0,15).entries())console.log('R15_SWING_SURVIVOR',JSON.stringify({rank:i+1,p:x.p,train:c(x.train),validation:c(x.validation),test:c(x.test!)}));if(!survivors.length)console.log('R15_SWING_NO_SURVIVOR');}

function buildGrid(){const o:P[]=[];for(const sideMode of ['BOTH','BUY'] as const){for(const lb of [16,32,64,96,192,480])for(const th of [.15,.30,.60,1.0])for(const hold of [16,32,64,96,192])for(const vol of [.5,.8,1.0])o.push({family:'TSMOM',lookback:lb,threshold:th,stopAtr:0,rr:0,holdBars:hold,volFilter:vol,sideMode});for(const stop of [1.5,2,3])for(const rr of [1.5,2,3,4])for(const hold of [32,64,96,192])for(const vol of [.5,.8,1])o.push({family:'DUAL_TREND',lookback:0,threshold:0,stopAtr:stop,rr,holdBars:hold,volFilter:vol,sideMode});for(const lb of [24,48,96,192])for(const stop of [1.5,2,3])for(const rr of [1.5,2,3])for(const hold of [32,64,96,192])o.push({family:'DONCHIAN',lookback:lb,threshold:0,stopAtr:stop,rr,holdBars:hold,volFilter:.7,sideMode});for(const lb of [4,8,16])for(const th of [.4,.7,1.0,1.5])for(const stop of [1.5,2.5])for(const rr of [1.5,2.5,3.5])o.push({family:'VOL_BREAKOUT',lookback:lb,threshold:th,stopAtr:stop,rr,holdBars:64,volFilter:1.1,sideMode});for(const stop of [1.5,2,3])for(const rr of [1.5,2,3])for(const hold of [32,64,96,192])o.push({family:'PULLBACK_4H',lookback:0,threshold:0,stopAtr:stop,rr,holdBars:hold,volFilter:.6,sideMode});}return o;}
function sim(f:F[],start:number,end:number,p:P):M{let bal=INITIAL,peak=INITIAL,dd=0,w=0,gp=0,gl=0,n=0,hours=0,i=Math.max(500,start);while(i<end-2&&bal>1){const s=signal(f,i,p);if(!s){i++;continue;}const e=i+1,entry=f[e].open*(1+s.side*(SPREAD_PCT/2+SLIP_PCT)/100),notional=bal*MARGIN_PCT/100*LEVERAGE,qty=notional/entry,entryFee=notional*FEE_PCT/100;let x=Math.min(end,e+p.holdBars),exit=f[x].close;if(s.stopDist>0){const sl=entry-s.side*s.stopDist,tp=entry+s.side*s.stopDist*s.rr;for(let j=e;j<=x;j++){const b=f[j],hs=s.side===1?b.low<=sl:b.high>=sl,ht=s.side===1?b.high>=tp:b.low<=tp;if(hs){exit=sl;x=j;break;}if(ht){exit=tp;x=j;break;}}}exit*=1-s.side*(SPREAD_PCT/2+SLIP_PCT)/100;const gross=s.side===1?(exit-entry)*qty:(entry-exit)*qty,exitFee=qty*exit*FEE_PCT/100,heldHours=Math.max(.25,(x-e+1)*.25),funding=notional*FUNDING_ALLOWANCE_8H_PCT/100*Math.floor(heldHours/8),pnl=gross-entryFee-exitFee-funding;bal+=pnl;n++;hours+=heldHours;if(pnl>0){w++;gp+=pnl}else gl+=Math.abs(pnl);peak=Math.max(peak,bal);dd=Math.max(dd,(peak-bal)/peak*100);i=Math.max(i+1,x+1);}return{trades:n,wins:w,winRate:n?w/n*100:0,pf:gl>0?gp/gl:gp>0?99:0,returnPct:(bal-INITIAL)/INITIAL*100,dd,balance:bal,expectancy:n?(bal-INITIAL)/n:0,avgHours:n?hours/n:0};}
function signal(f:F[],i:number,p:P):{side:Side;stopDist:number;rr:number}|null{const b=f[i];if(!(b.atr>0)||b.atrPct<.02)return null;const allow=(side:Side)=>p.sideMode==='BOTH'||side===1;if(p.family==='TSMOM'){if(i<p.lookback)return null;const r=(b.close-f[i-p.lookback].close)/f[i-p.lookback].close*100;if(Math.abs(r)<p.threshold||b.atrPct<mean(f.slice(Math.max(0,i-100),i).map(x=>x.atrPct))*p.volFilter)return null;const side:Side=r>0?1:-1;if(!allow(side))return null;const regime=side===1?b.h4e20>=b.h4e50:b.h4e20<=b.h4e50;if(!regime)return null;return{side,stopDist:0,rr:0};}
if(p.family==='DUAL_TREND'){const long=b.h4e20>b.h4e50&&b.h4e50>b.h4e200&&b.h4slope>0&&b.h1e20>b.h1e50&&b.ema20>b.ema50&&b.rsi>=48&&b.rsi<=72,short=b.h4e20<b.h4e50&&b.h4e50<b.h4e200&&b.h4slope<0&&b.h1e20<b.h1e50&&b.ema20<b.ema50&&b.rsi<=52&&b.rsi>=28;if(!long&&!short)return null;const side:Side=long?1:-1;if(!allow(side))return null;return{side,stopDist:b.atr*p.stopAtr,rr:p.rr};}
if(p.family==='DONCHIAN'){const q=f.slice(i-p.lookback,i);if(q.length<p.lookback)return null;const hi=Math.max(...q.map(x=>x.high)),lo=Math.min(...q.map(x=>x.low)),long=b.close>hi&&b.h4e20>=b.h4e50,short=b.close<lo&&b.h4e20<=b.h4e50;if(!long&&!short)return null;const side:Side=long?1:-1;if(!allow(side))return null;return{side,stopDist:b.atr*p.stopAtr,rr:p.rr};}
if(p.family==='VOL_BREAKOUT'){if(i<p.lookback)return null;const r=(b.close-f[i-p.lookback].close)/f[i-p.lookback].close*100,vol=b.atrPct/Math.max(.0001,mean(f.slice(Math.max(0,i-100),i).map(x=>x.atrPct)));if(Math.abs(r)<p.threshold||vol<p.volFilter)return null;const side:Side=r>0?1:-1;if(!allow(side))return null;return{side,stopDist:b.atr*p.stopAtr,rr:p.rr};}
const prev=f[i-1],long=b.h4e20>b.h4e50&&b.h4e50>b.h4e200&&b.h4slope>0&&prev.low<=b.ema20+b.atr*.3&&b.close>b.ema20&&b.close>b.open,short=b.h4e20<b.h4e50&&b.h4e50<b.h4e200&&b.h4slope<0&&prev.high>=b.ema20-b.atr*.3&&b.close<b.ema20&&b.close<b.open;if(!long&&!short)return null;const side:Side=long?1:-1;if(!allow(side))return null;return{side,stopDist:b.atr*p.stopAtr,rr:p.rr};}
function features(m15:Candle[],h1:Candle[],h4:Candle[]):F[]{const c=m15.map(x=>x.close),e20=ema(c,20),e50=ema(c,50),e200=ema(c,200),a=atr(m15,14),r=rsi(c,14),h1c=h1.map(x=>x.close),h1e20=ema(h1c,20),h1e50=ema(h1c,50),h1e200=ema(h1c,200),h1a=atr(h1,14),h4c=h4.map(x=>x.close),h4e20=ema(h4c,20),h4e50=ema(h4c,50),h4e200=ema(h4c,200),h4a=atr(h4,14);let i1=0,i4=0;return m15.map((x,i)=>{const close=x.time+M15;while(i1+1<h1.length&&h1[i1+1].time+H1<=close)i1++;while(i4+1<h4.length&&h4[i4+1].time+H4<=close)i4++;return{...x,atr:a[i],atrPct:x.close>0?a[i]/x.close*100:0,ema20:e20[i],ema50:e50[i],ema200:e200[i],rsi:r[i],volAvg:mean(m15.slice(Math.max(0,i-19),i+1).map(y=>y.volume)),h1e20:h1e20[i1]??0,h1e50:h1e50[i1]??0,h1e200:h1e200[i1]??0,h1atr:h1a[i1]??0,h4e20:h4e20[i4]??0,h4e50:h4e50[i4]??0,h4e200:h4e200[i4]??0,h4atr:h4a[i4]??0,h4slope:i4>=2?(h4e20[i4]??0)-(h4e20[i4-2]??0):0};});}
function survival(x:C){const t=x.test!;return t.returnPct-t.dd*.6+Math.min(t.pf,3)*3+Math.min(t.trades,50)*.02}function c(m:M){return{trades:m.trades,winRate:Number(m.winRate.toFixed(2)),pf:Number(m.pf.toFixed(3)),returnPct:Number(m.returnPct.toFixed(3)),dd:Number(m.dd.toFixed(3)),balance:Number(m.balance.toFixed(4)),expectancy:Number(m.expectancy.toFixed(5)),avgHours:Number(m.avgHours.toFixed(2))}}
function aggregate(rows:Candle[],bucket:number){const map=new Map<number,Candle>();for(const x of rows){const t=Math.floor(x.time/bucket)*bucket,b=map.get(t);if(!b)map.set(t,{...x,time:t});else{b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=x.volume;}}return[...map.values()].sort((a,b)=>a.time-b.time)}function ema(v:number[],p:number){const o=new Array(v.length).fill(0);if(!v.length)return o;const k=2/(p+1);o[0]=v[0];for(let i=1;i<v.length;i++)o[i]=v[i]*k+o[i-1]*(1-k);return o}function atr(r:Candle[],p:number){const o=new Array(r.length).fill(0);if(!r.length)return o;o[0]=r[0].high-r[0].low;for(let i=1;i<r.length;i++){const tr=Math.max(r[i].high-r[i].low,Math.abs(r[i].high-r[i-1].close),Math.abs(r[i].low-r[i-1].close));o[i]=i<p?(o[i-1]*i+tr)/(i+1):(o[i-1]*(p-1)+tr)/p;}return o}function rsi(v:number[],p:number){const o=new Array(v.length).fill(50);let g=0,l=0;for(let i=1;i<v.length;i++){const d=v[i]-v[i-1];if(i<=p){if(d>=0)g+=d;else l-=d;if(i===p){g/=p;l/=p}}else{g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}if(i>=p)o[i]=l<=1e-12?(g>0?100:50):100-100/(1+g/l)}return o}function mean(v:number[]){return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}
function monthKeys(start:number,end:number){const o:string[]=[];let d=new Date(Date.UTC(new Date(start).getUTCFullYear(),new Date(start).getUTCMonth(),1)),z=new Date(Date.UTC(new Date(end).getUTCFullYear(),new Date(end).getUTCMonth(),1));while(d<=z){o.push(`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`);d=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1));}return o;}async function fetchVision(symbol:string,start:number,end:number,dir:string):Promise<Candle[]>{const out:Candle[]=[];for(const month of monthKeys(start,end)){const fn=`${symbol}-1m-${month}.zip`,res=await fetch(`${VISION}/${symbol}/1m/${fn}`);if(res.status===404)continue;if(!res.ok)throw new Error(`VISION_${res.status}:${fn}`);const file=path.join(dir,fn);await writeFile(file,Buffer.from(await res.arrayBuffer()));const csv=execFileSync('unzip',['-p',file],{encoding:'utf8',maxBuffer:256*1024*1024});for(const line of csv.split(/\r?\n/)){if(!line.trim())continue;const a=line.split(','),raw=Number(a[0]);if(!Number.isFinite(raw))continue;const time=raw>1e17?Math.floor(raw/1_000_000):raw>1e14?Math.floor(raw/1000):raw,x:Candle={time,open:Number(a[1]),high:Number(a[2]),low:Number(a[3]),close:Number(a[4]),volume:Number(a[5]??0)};if([x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)&&time>=start&&time<=end)out.push(x)}}const map=new Map(out.map(x=>[x.time,x]));return[...map.values()].sort((a,b)=>a.time-b.time)}
main().catch(e=>{console.error('R15_SWING_ERROR',e instanceof Error?e.message:String(e));process.exit(1)});
