import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
type Bar={time:number;open:number;high:number;low:number;close:number;volume:number}; type Side=1|-1|0;
type Stats={trades:number;wins:number;winRate:number;profitFactor:number;returnPct:number;maxDD:number;expectancy:number;perDay:number;final50:number};
const S='XAUUSDT',TF='5m',DAY=86400000,COST=.145,EX=.10,FUND8H=.005;const BASE=`https://data.binance.vision/data/futures/um/monthly/klines/${S}/${TF}`;
async function load(){const d=await mkdtemp(path.join(os.tmpdir(),'ts100-')),o:Bar[]=[];for(let m=1;m<=8;m++){const ym=`2026-${String(m).padStart(2,'0')}`,fn=`${S}-${TF}-${ym}.zip`,r=await fetch(`${BASE}/${fn}`);if(!r.ok)continue;const f=path.join(d,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));for(const l of execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:256*1024*1024}).split(/\r?\n/)){if(!l.trim())continue;const c=l.split(','),v=[+c[0],+c[1],+c[2],+c[3],+c[4],+c[5]];if(v.every(Number.isFinite))o.push({time:v[0],open:v[1],high:v[2],low:v[3],close:v[4],volume:v[5]});}}return o.sort((a,b)=>a.time-b.time);}
function sma(b:Bar[],i:number,n:number,k:'close'|'volume'='close'){if(i<n-1)return NaN;let s=0;for(let j=i-n+1;j<=i;j++)s+=b[j][k];return s/n}function ema(b:Bar[],i:number,n:number){if(i<n)return NaN;const a=2/(n+1);let e=b[i-n].close;for(let j=i-n+1;j<=i;j++)e=a*b[j].close+(1-a)*e;return e}function rsi(b:Bar[],i:number,n:number){if(i<n)return NaN;let g=0,l=0;for(let j=i-n+1;j<=i;j++){const d=b[j].close-b[j-1].close;if(d>0)g+=d;else l-=d}return l?100-100/(1+g/l):100}function roc(b:Bar[],i:number,n:number){return i>=n?(b[i].close/b[i-n].close-1)*100:NaN}function hi(b:Bar[],i:number,n:number){let x=-Infinity;for(let j=Math.max(0,i-n);j<i;j++)x=Math.max(x,b[j].high);return x}function lo(b:Bar[],i:number,n:number){let x=Infinity;for(let j=Math.max(0,i-n);j<i;j++)x=Math.min(x,b[j].low);return x}function std(b:Bar[],i:number,n:number){const m=sma(b,i,n);if(!Number.isFinite(m))return NaN;let s=0;for(let j=i-n+1;j<=i;j++)s+=(b[j].close-m)**2;return Math.sqrt(s/n)}function rangeLoc(x:Bar){const r=x.high-x.low;return r?(x.close-x.low)/r:.5}function candle(b:Bar[],i:number){if(i<1)return 0;const x=b[i],p=b[i-1],bd=Math.abs(x.close-x.open),rg=x.high-x.low;if(x.close>x.open&&p.close<p.open&&x.close>=p.open&&x.open<=p.close)return 1;if(x.close<x.open&&p.close>p.open&&x.open>=p.close&&x.close<=p.open)return -1;if(rg){const u=x.high-Math.max(x.open,x.close),d=Math.min(x.open,x.close)-x.low;if(d>bd*2.2&&u<bd)return 1;if(u>bd*2.2&&d<bd)return -1}return 0}
function families(b:Bar[],i:number){const F:number[][]=Array.from({length:20},()=>[]),ps=[5,8,13,21,34],x=b[i];for(let z=0;z<5;z++){const p=ps[z],e=ema(b,i,p),e2=ema(b,i,p*2),s=sma(b,i,p),s2=sma(b,i,p*2),R=rsi(b,i,Math.max(7,p)),q=roc(b,i,p),D=std(b,i,Math.max(10,p)),hh=hi(b,i,p),ll=lo(b,i,p),vm=sma(b,i,Math.max(12,p),'volume');F[0].push(e>e2?1:e<e2?-1:0);F[1].push(s>s2?1:s<s2?-1:0);F[2].push(x.close>e?1:x.close<e?-1:0);F[3].push(R>55?1:R<45?-1:0);F[4].push(R<30?1:R>70?-1:0);F[5].push(q>.15?1:q<-.15?-1:0);F[6].push(x.close>hh?1:x.close<ll?-1:0);F[7].push(x.high>=hh&&x.close<hh?-1:x.low<=ll&&x.close>ll?1:0);F[8].push(Number.isFinite(D)&&x.close>s+1.5*D?1:x.close<s-1.5*D?-1:0);F[9].push(Number.isFinite(D)&&x.close<s-1.8*D?1:x.close>s+1.8*D?-1:0);F[10].push(candle(b,i));F[11].push(rangeLoc(x)>.72?1:rangeLoc(x)<.28?-1:0);F[12].push(x.volume>vm*1.3&&x.close>x.open?1:x.volume>vm*1.3&&x.close<x.open?-1:0);const mid=(hh+ll)/2;F[13].push(x.close>mid&&q>0?1:x.close<mid&&q<0?-1:0);F[14].push(x.low<ll&&x.close>ll?1:x.high>hh&&x.close<hh?-1:0);F[15].push(i>=p*2&&x.close>b[i-p].close&&b[i-p].close>b[i-p*2].close?1:i>=p*2&&x.close<b[i-p].close&&b[i-p].close<b[i-p*2].close?-1:0);F[16].push(x.close>hh&&x.volume>vm*1.2?1:x.close<ll&&x.volume>vm*1.2?-1:0);const pos=hh>ll?(x.close-ll)/(hh-ll):.5;F[17].push(pos>.618?1:pos<.382?-1:0);F[18].push(R>50&&q>0?1:R<50&&q<0?-1:0);F[19].push(e>s?1:e<s?-1:0);}return F.map(v=>{const s=v.reduce((a,c)=>a+c,0);return s>=2?1:s<=-2?-1:0})}
function tsmom(b:Bar[],i:number,thr:number):Side{const n16=192,n4=48;if(i<600)return 0;const m=(b[i].close/b[i-n16].close-1)*100,e20=ema(b,i,20*n4),e50=ema(b,i,50*n4);if(m>=thr&&e20>e50)return 1;if(m<=-thr&&e20<e50)return -1;return 0}
function run(b:Bar[],s:number,e:number,c:{thr:number;minFam:number;holdH:number;delayH:number;session:boolean}){let eq=100,pk=100,dd=0,gp=0,gl=0,w=0,sum=0,tr=0,next=s;for(let i=Math.max(s,2500);i<e-2;i++){if(i<next)continue;const d=tsmom(b,i,c.thr);if(!d)continue;if(c.session){const h=new Date(b[i].time).getUTCHours();if(h<7||h>20)continue;}let entryI=-1;for(let j=i;j<=Math.min(e-2,i+c.delayH*12);j++){const f=families(b,j),n=f.filter(x=>x===d).length,opp=f.filter(x=>x===-d).length;if(n>=c.minFam&&n>opp){entryI=j+1;break}}if(entryI<0)continue;const exitI=Math.min(e-1,entryI+c.holdH*12),entry=b[entryI].open,exit=b[exitI].close,gross=d===1?(exit/entry-1)*100:(entry/exit-1)*100,holdHours=(b[exitI].time-b[entryI].time)/3600000,fund=Math.ceil(holdHours/8)*FUND8H,net=gross-COST-fund,ar=net*EX;eq*=1+ar/100;pk=Math.max(pk,eq);dd=Math.max(dd,(pk-eq)/pk*100);sum+=ar;tr++;if(ar>0){w++;gp+=ar}else gl+=Math.abs(ar);next=exitI+1;}const days=Math.max(1,(b[e-1].time-b[s].time)/DAY);return{trades:tr,wins:w,winRate:tr?w/tr*100:0,profitFactor:gl?gp/gl:gp?99:0,returnPct:eq-100,maxDD:dd,expectancy:tr?sum/tr:0,perDay:tr/days,final50:50*eq/100} as Stats}
function pass(x:Stats,min:number){return x.trades>=min&&x.returnPct>0&&x.profitFactor>1&&x.expectancy>0}
async function main(){const b=await load(),n=b.length,tr=Math.floor(n*.5),va=Math.floor(n*.75);console.log('BARS',n,new Date(b[0].time).toISOString(),new Date(b.at(-1)!.time).toISOString());const cfg=[] as any[];for(const thr of [.8,1,1.2,1.5])for(const minFam of [5,6,7,8])for(const holdH of [12,16,20,24])for(const delayH of [0,1,2,4])for(const session of [false,true])cfg.push({thr,minFam,holdH,delayH,session});let best:any=null,tp=0,vp=0;for(const c of cfg){const a=run(b,0,tr,c);if(!pass(a,12))continue;tp++;const v=run(b,tr,va,c);if(!pass(v,6))continue;vp++;const score=a.returnPct+v.returnPct+Math.min(3,a.profitFactor)+Math.min(3,v.profitFactor)-a.maxDD-v.maxDD;if(!best||score>best.score)best={c,a,v,score}}console.log('SEARCH',JSON.stringify({configs:cfg.length,trainPositive:tp,validationPositive:vp}));if(!best){console.log('TS100_RESULT',JSON.stringify({survived:false,reason:'NO_TSMOM_PLUS_5_FAMILIES_SURVIVED'}));return;}const te=run(b,va,n,best.c);console.log('TS100_RESULT',JSON.stringify({survived:pass(te,6),config:best.c,train:best.a,validation:best.v,test:te,costPct:COST,funding8hPct:FUND8H,exposure:EX,strategies:100,families:20}));}
main().catch(e=>{console.error(e);process.exit(1)});