import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

type Bar={time:number;open:number;high:number;low:number;close:number;volume:number};
type Side=1|-1|0;
type Trade={entryTime:number;exitTime:number;side:1|-1;marketNetPct:number;accountRetPct:number;reason:'TP'|'SL'|'TIME'};
type Stats={trades:number;wins:number;winRate:number;profitFactor:number;accountReturnPct:number;maxDrawdownPct:number;expectancyPct:number;tradesPerDay:number;final50:number};
type Mgmt={stopAtr:number;rr:number;hold:number;mode:'RAW'|'TREND'|'SESSION'|'TREND_SESSION'};
const SYMBOL='XAUUSDT', TF='5m', COST=0.145, EXPOSURE=.10, DAY=86400000;
const BASE=`https://data.binance.vision/data/futures/um/monthly/klines/${SYMBOL}/${TF}`;

async function load():Promise<Bar[]>{const dir=await mkdtemp(path.join(os.tmpdir(),'xau100-'));const out:Bar[]=[];for(let m=1;m<=8;m++){const ym=`2026-${String(m).padStart(2,'0')}`,fn=`${SYMBOL}-${TF}-${ym}.zip`,r=await fetch(`${BASE}/${fn}`);if(!r.ok){console.log('MISS',ym,r.status);continue;}const f=path.join(dir,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));const csv=execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:256*1024*1024});let n=0;for(const line of csv.split(/\r?\n/)){if(!line.trim())continue;const c=line.split(',');const t=+c[0],o=+c[1],h=+c[2],l=+c[3],cl=+c[4],v=+c[5];if([t,o,h,l,cl,v].every(Number.isFinite)){out.push({time:t,open:o,high:h,low:l,close:cl,volume:v});n++;}}console.log('MONTH',ym,n);}out.sort((a,b)=>a.time-b.time);const d=new Map<number,Bar>();for(const b of out)d.set(b.time,b);return [...d.values()];}
function sma(b:Bar[],i:number,n:number,k:'close'|'volume'='close'){if(i<n-1)return NaN;let s=0;for(let j=i-n+1;j<=i;j++)s+=b[j][k];return s/n;}
function ema(b:Bar[],i:number,n:number){if(i<n)return NaN;const a=2/(n+1);let e=b[i-n].close;for(let j=i-n+1;j<=i;j++)e=a*b[j].close+(1-a)*e;return e;}
function atr(b:Bar[],i:number,n=14){if(i<n)return NaN;let s=0;for(let j=i-n+1;j<=i;j++){const p=b[j-1].close;s+=Math.max(b[j].high-b[j].low,Math.abs(b[j].high-p),Math.abs(b[j].low-p));}return s/n;}
function rsi(b:Bar[],i:number,n=14){if(i<n)return NaN;let g=0,l=0;for(let j=i-n+1;j<=i;j++){const d=b[j].close-b[j-1].close;if(d>0)g+=d;else l-=d;}return l?100-100/(1+g/l):100;}
function roc(b:Bar[],i:number,n:number){return i>=n?(b[i].close/b[i-n].close-1)*100:NaN;}
function hi(b:Bar[],i:number,n:number){let x=-Infinity;for(let j=i-n;j<i;j++)if(j>=0)x=Math.max(x,b[j].high);return x;}
function lo(b:Bar[],i:number,n:number){let x=Infinity;for(let j=i-n;j<i;j++)if(j>=0)x=Math.min(x,b[j].low);return x;}
function std(b:Bar[],i:number,n:number){const m=sma(b,i,n);if(!Number.isFinite(m))return NaN;let s=0;for(let j=i-n+1;j<=i;j++)s+=(b[j].close-m)**2;return Math.sqrt(s/n);}
function stoch(b:Bar[],i:number,n:number){const h=hi(b,i+1,n),l=lo(b,i+1,n);return h>l?(b[i].close-l)/(h-l)*100:50;}
function candle(b:Bar[],i:number,kind:'engulf'|'pin'){if(i<1)return 0;const x=b[i],p=b[i-1],body=Math.abs(x.close-x.open),range=x.high-x.low;if(kind==='engulf'){if(x.close>x.open&&p.close<p.open&&x.close>=p.open&&x.open<=p.close)return 1;if(x.close<x.open&&p.close>p.open&&x.open>=p.close&&x.close<=p.open)return -1;}else if(range>0){const up=x.high-Math.max(x.open,x.close),dn=Math.min(x.open,x.close)-x.low;if(dn>body*2.2&&up<body*.8)return 1;if(up>body*2.2&&dn<body*.8)return -1;}return 0;}
function stratVotes(b:Bar[],i:number){const fam:number[][]=Array.from({length:20},()=>[]);const ps=[5,8,13,21,34];for(let k=0;k<5;k++){const p=ps[k],x=b[i],a=atr(b,i,14);const e1=ema(b,i,p),e2=ema(b,i,p*2),s1=sma(b,i,p),s2=sma(b,i,p*2),R=rsi(b,i,Math.max(7,p)),q=roc(b,i,p),D=std(b,i,Math.max(10,p));fam[0].push(e1>e2?1:e1<e2?-1:0);fam[1].push(s1>s2?1:s1<s2?-1:0);fam[2].push(x.close>e1?1:x.close<e1?-1:0);fam[3].push(R>55?1:R<45?-1:0);fam[4].push(R<30?1:R>70?-1:0);fam[5].push(q>.15?1:q<-.15?-1:0);fam[6].push(i>=p*2?(x.close>b[i-p].close&&b[i-p].close>b[i-p*2].close?1:x.close<b[i-p].close&&b[i-p].close<b[i-p*2].close?-1:0):0);fam[7].push(x.close>hi(b,i,p)?1:x.close<lo(b,i,p)?-1:0);fam[8].push(x.high>=hi(b,i,p)&&x.close<hi(b,i,p)?-1:x.low<=lo(b,i,p)&&x.close>lo(b,i,p)?1:0);fam[9].push(Number.isFinite(D)&&x.close>s1+1.5*D?1:x.close<s1-1.5*D?-1:0);fam[10].push(Number.isFinite(D)&&x.close<s1-1.8*D?1:x.close>s1+1.8*D?-1:0);const S=stoch(b,i,Math.max(9,p));fam[11].push(S>70?1:S<30?-1:0);const fast=ema(b,i,Math.max(5,p)),slow=ema(b,i,Math.max(10,p*2)),sig=i>3?ema(b,i-3,Math.max(5,p))-ema(b,i-3,Math.max(10,p*2)):0,m=fast-slow;fam[12].push(m>sig?1:m<sig?-1:0);const prevA=atr(b,i-1,14);fam[13].push(Number.isFinite(a)&&Number.isFinite(prevA)&&a>prevA*1.15?(x.close>x.open?1:-1):0);fam[14].push(candle(b,i,'engulf'));fam[15].push(candle(b,i,'pin'));const hh=hi(b,i,p),ll=lo(b,i,p),mid=(hh+ll)/2;fam[16].push(x.close>hh?1:x.close<ll?-1:(x.low<mid&&x.close>mid?1:x.high>mid&&x.close<mid?-1:0));fam[17].push(x.close>hh&&x.volume>sma(b,i,Math.max(10,p),'volume')*1.2?1:x.close<ll&&x.volume>sma(b,i,Math.max(10,p),'volume')*1.2?-1:0);const rng=hh-ll,pos=rng>0?(x.close-ll)/rng:.5;fam[18].push(pos>.618&&q>0?1:pos<.382&&q<0?-1:0);const vm=sma(b,i,Math.max(12,p),'volume');fam[19].push(x.volume>vm*1.5&&rangeLoc(x)>.7?1:x.volume>vm*1.5&&rangeLoc(x)<.3?-1:0);}return fam.map(v=>{const s=v.reduce((a,c)=>a+c,0);return s>=2?1:s<=-2?-1:0;});}
function rangeLoc(x:Bar){const r=x.high-x.low;return r?(x.close-x.low)/r:.5;}
function sessionOK(t:number){const h=new Date(t).getUTCHours();return h>=7&&h<=20;}
function sideAt(b:Bar[],i:number,mode:Mgmt['mode']):Side{const f=stratVotes(b,i),bu=f.filter(x=>x===1).length,se=f.filter(x=>x===-1).length;let s:Side=bu>=5&&bu>se?1:se>=5&&se>bu?-1:0;if(!s)return 0;if(mode==='SESSION'||mode==='TREND_SESSION'){if(!sessionOK(b[i].time))return 0;}if(mode==='TREND'||mode==='TREND_SESSION'){const e20=ema(b,i,240),e50=ema(b,i,600);if(!Number.isFinite(e20)||!Number.isFinite(e50))return 0;if(s===1&&e20<=e50)return 0;if(s===-1&&e20>=e50)return 0;}return s;}
function calc(t:Trade[],b:Bar[],s:number,e:number):Stats{let eq=100,pk=100,dd=0,gp=0,gl=0,w=0,sum=0;for(const x of t){eq*=1+x.accountRetPct/100;pk=Math.max(pk,eq);dd=Math.max(dd,(pk-eq)/pk*100);sum+=x.accountRetPct;if(x.accountRetPct>0){w++;gp+=x.accountRetPct}else gl+=Math.abs(x.accountRetPct);}const days=Math.max(1,(b[e-1].time-b[s].time)/DAY);return{trades:t.length,wins:w,winRate:t.length?w/t.length*100:0,profitFactor:gl?gp/gl:gp?99:0,accountReturnPct:eq-100,maxDrawdownPct:dd,expectancyPct:t.length?sum/t.length:0,tradesPerDay:t.length/days,final50:50*eq/100};}
function run(b:Bar[],m:Mgmt,s:number,e:number):Stats{const t:Trade[]=[];let next=s;for(let i=Math.max(s,650);i<e-2;i++){if(i<next)continue;const side=sideAt(b,i,m.mode);if(!side)continue;const A=atr(b,i,14);if(!Number.isFinite(A)||A<=0)continue;const ei=i+1,entry=b[ei].open,sl=side===1?entry-m.stopAtr*A:entry+m.stopAtr*A,risk=Math.abs(entry-sl),tp=side===1?entry+m.rr*risk:entry-m.rr*risk;let exit=b[Math.min(e-1,ei+m.hold)].close,xi=Math.min(e-1,ei+m.hold),reason:Trade['reason']='TIME';for(let j=ei;j<=Math.min(e-1,ei+m.hold);j++){const x=b[j];if(side===1){if(x.low<=sl){exit=sl;xi=j;reason='SL';break;}if(x.high>=tp){exit=tp;xi=j;reason='TP';break;}}else{if(x.high>=sl){exit=sl;xi=j;reason='SL';break;}if(x.low<=tp){exit=tp;xi=j;reason='TP';break;}}}const gross=side===1?(exit-entry)/entry*100:(entry-exit)/entry*100,net=gross-COST,ar=net*EXPOSURE;t.push({entryTime:b[ei].time,exitTime:b[xi].time,side,marketNetPct:net,accountRetPct:ar,reason});next=xi+1;}return calc(t,b,s,e);}
function pass(x:Stats,min:number){return x.trades>=min&&x.accountReturnPct>0&&x.profitFactor>1&&x.expectancyPct>0;}
async function main(){const b=await load();console.log('BARS',b.length,'FROM',new Date(b[0].time).toISOString(),'TO',new Date(b.at(-1)!.time).toISOString());if(b.length<5000)throw new Error('NOT_ENOUGH_DATA');const n=b.length,tr=Math.floor(n*.5),va=Math.floor(n*.75);const mg:Mgmt[]=[];for(const stopAtr of [.8,1.2,1.6,2])for(const rr of [1.2,1.5,2,2.5,3])for(const hold of [12,24,48,96])for(const mode of ['RAW','TREND','SESSION','TREND_SESSION'] as const)mg.push({stopAtr,rr,hold,mode});let best:any=null,posT=0,posV=0;for(const m of mg){const a=run(b,m,0,tr);if(!pass(a,20))continue;posT++;const v=run(b,m,tr,va);if(!pass(v,10))continue;posV++;const score=a.accountReturnPct+v.accountReturnPct+Math.min(3,a.profitFactor)+Math.min(3,v.profitFactor)-a.maxDrawdownPct-v.maxDrawdownPct;if(!best||score>best.score)best={m,a,v,score};}console.log('SEARCH',JSON.stringify({strategies:100,families:20,minConfluenceFamilies:5,managementConfigs:mg.length,trainPositive:posT,validationPositive:posV}));if(!best){console.log('ENSEMBLE_RESULT',JSON.stringify({survived:false,reason:'NO_5_FAMILY_ENSEMBLE_SURVIVED_TRAIN_VALIDATION',costPct:COST,exposure:EXPOSURE}));return;}const te=run(b,best.m,va,n);console.log('ENSEMBLE_RESULT',JSON.stringify({survived:pass(te,10),management:best.m,train:best.a,validation:best.v,test:te,costPct:COST,exposure:EXPOSURE,strategies:100,families:20,minConfluenceFamilies:5}));}
main().catch(e=>{console.error('ENSEMBLE_ERROR',e instanceof Error?e.message:String(e));process.exit(1);});