import { execFileSync } from 'node:child_process';
import { mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

type Bar={time:number;open:number;high:number;low:number;close:number;volume:number};
type Vote={name:string;family:string;side:'BUY'|'SELL'|null};
type Stats={trades:number;wins:number;winRate:number;profitFactor:number;accountReturnPct:number;maxDrawdownPct:number;final50:number;avgVotes:number;tradesPerDay:number};
const SYMBOL='XAUUSDT', DAY=86400000, DAYS=180, COST=0.145, EXPOSURE=.10;
const BASE=`https://data.binance.vision/data/futures/um/daily/klines/${SYMBOL}/1m`;
async function day(day:string,dir:string){const fn=`${SYMBOL}-1m-${day}.zip`,r=await fetch(`${BASE}/${fn}`);if(r.status===404)return[] as Bar[];if(!r.ok)throw new Error(`VISION_${r.status}:${day}`);const f=path.join(dir,fn);await writeFile(f,Buffer.from(await r.arrayBuffer()));const csv=execFileSync('unzip',['-p',f],{encoding:'utf8',maxBuffer:128*1024*1024});const out:Bar[]=[];for(const l of csv.split(/\r?\n/)){if(!l.trim())continue;const c=l.split(',');const t=+c[0],o=+c[1],h=+c[2],lo=+c[3],cl=+c[4],v=+c[5];if([t,o,h,lo,cl,v].every(Number.isFinite))out.push({time:t,open:o,high:h,low:lo,close:cl,volume:v});}return out;}
function agg(src:Bar[],ms:number){const m=new Map<number,Bar>();for(const x of src){const k=Math.floor(x.time/ms)*ms;let b=m.get(k);if(!b){b={time:k,open:x.open,high:x.high,low:x.low,close:x.close,volume:0};m.set(k,b);}b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=x.volume;}return[...m.values()].sort((a,b)=>a.time-b.time)}
function ema(v:number[],p:number){const o:number[]=[];let e=v[0]??0,k=2/(p+1);for(const x of v){e=x*k+e*(1-k);o.push(e)}return o}
function sma(v:number[],p:number,i:number){let s=0,n=0;for(let j=Math.max(0,i-p+1);j<=i;j++){s+=v[j];n++}return s/n}
function atr(b:Bar[],p=14){const a:number[]=[];for(let i=0;i<b.length;i++){const tr=i?Math.max(b[i].high-b[i].low,Math.abs(b[i].high-b[i-1].close),Math.abs(b[i].low-b[i-1].close)):b[i].high-b[i].low;a[i]=i?((a[i-1]*(Math.min(i,p)-1)+tr)/Math.min(i,p)):tr;}return a}
function rsi(v:number[],p=14){const o=new Array(v.length).fill(50);let g=0,l=0;for(let i=1;i<v.length;i++){const d=v[i]-v[i-1];g+=Math.max(0,d);l+=Math.max(0,-d);if(i>=p){if(i>p){const od=v[i-p]-v[i-p-1];g-=Math.max(0,od);l-=Math.max(0,-od)}o[i]=l?100-100/(1+g/l):100}}return o}
function hi(b:Bar[],i:number,n:number){let x=-Infinity;for(let j=Math.max(0,i-n);j<i;j++)x=Math.max(x,b[j].high);return x}
function lo(b:Bar[],i:number,n:number){let x=Infinity;for(let j=Math.max(0,i-n);j<i;j++)x=Math.min(x,b[j].low);return x}
function slope(v:number[],i:number,n:number){if(i<n)return 0;return (v[i]-v[i-n])/Math.max(1e-9,Math.abs(v[i-n]))*100}
function votes(b:Bar[],i:number,tf4:Bar[],j4:number):Vote[]{const c=b.map(x=>x.close),v=b.map(x=>x.volume),e9=ema(c,9),e20=ema(c,20),e50=ema(c,50),e100=ema(c,100),e200=ema(c,200),rr=rsi(c,14),aa=atr(b,14);const c4=tf4.map(x=>x.close),e4_20=ema(c4,20),e4_50=ema(c4,50);const x=b[i],res:Vote[]=[];const add=(name:string,f:string,condB:boolean,condS:boolean)=>res.push({name,family:f,side:condB?'BUY':condS?'SELL':null});
// 20 trend variants
for(const [n,a,d] of [[1,e9,e20],[2,e9,e50],[3,e20,e50],[4,e20,e100],[5,e20,e200],[6,e50,e100],[7,e50,e200],[8,e100,e200]] as any[])add(`EMA_TREND_${n}`,'TREND',a[i]>d[i],a[i]<d[i]);
for(const [n,p] of [[9,12],[10,24],[11,48],[12,72],[13,96],[14,144]] as any[])add(`SLOPE_${n}`,'TREND',slope(c,i,p)>.15,slope(c,i,p)<-.15);
add('4H_EMA20_50','TREND',e4_20[j4]>e4_50[j4],e4_20[j4]<e4_50[j4]);add('PRICE_EMA200','TREND',x.close>e200[i],x.close<e200[i]);add('EMA_STACK_FAST','TREND',e9[i]>e20[i]&&e20[i]>e50[i],e9[i]<e20[i]&&e20[i]<e50[i]);add('EMA_STACK_SLOW','TREND',e20[i]>e50[i]&&e50[i]>e200[i],e20[i]<e50[i]&&e50[i]<e200[i]);add('TREND_PRICE50','TREND',x.close>e50[i]&&slope(e50,i,12)>0,x.close<e50[i]&&slope(e50,i,12)<0);add('TREND_4H_PRICE','TREND',c4[j4]>e4_20[j4],c4[j4]<e4_20[j4]);
// 15 momentum
for(const [n,th] of [[1,55],[2,58],[3,60],[4,62],[5,65]] as any[])add(`RSI_MOM_${n}`,'MOMENTUM',rr[i]>th,rr[i]<100-th);
for(const [n,p,t] of [[6,6,.10],[7,12,.15],[8,24,.25],[9,48,.4],[10,96,.7]] as any[])add(`ROC_${n}`,'MOMENTUM',slope(c,i,p)>t,slope(c,i,p)<-t);
for(const [n,p] of [[11,6],[12,12],[13,24],[14,48],[15,72]] as any[])add(`MOM_CLOSE_${n}`,'MOMENTUM',x.close>c[i-p]&&x.close>e20[i],x.close<c[i-p]&&x.close<e20[i]);
// 15 breakout
for(const [n,p] of [[1,6],[2,12],[3,24],[4,36],[5,48],[6,72],[7,96],[8,144]] as any[])add(`DONCHIAN_${n}`,'BREAKOUT',x.close>hi(b,i,p),x.close<lo(b,i,p));
for(const [n,p] of [[9,12],[10,24],[11,48],[12,96]] as any[])add(`HIGHLOW_CLOSE_${n}`,'BREAKOUT',x.high>hi(b,i,p)&&x.close>(x.high+x.low)/2,x.low<lo(b,i,p)&&x.close<(x.high+x.low)/2);
add('ATR_BREAKOUT_1','BREAKOUT',x.close>hi(b,i,24)+.2*aa[i],x.close<lo(b,i,24)-.2*aa[i]);add('ATR_BREAKOUT_2','BREAKOUT',x.close>hi(b,i,48)+.3*aa[i],x.close<lo(b,i,48)-.3*aa[i]);add('VOL_BREAKOUT','BREAKOUT',x.close>hi(b,i,24)&&x.volume>sma(v,30,i)*1.5,x.close<lo(b,i,24)&&x.volume>sma(v,30,i)*1.5);
// 10 pullback
for(const [n,ep] of [[1,e9],[2,e20],[3,e50]] as any[])add(`PULLBACK_EMA_${n}`,'PULLBACK',c[i-1]<ep[i-1]&&x.close>ep[i]&&e20[i]>e50[i],c[i-1]>ep[i-1]&&x.close<ep[i]&&e20[i]<e50[i]);
for(const [n,k] of [[4,.5],[5,1],[6,1.5]] as any[])add(`PULLBACK_ATR_${n}`,'PULLBACK',e20[i]>e50[i]&&x.low<e20[i]+k*aa[i]&&x.close>e20[i],e20[i]<e50[i]&&x.high>e20[i]-k*aa[i]&&x.close<e20[i]);
add('RETEST_24','PULLBACK',c[i-1]<hi(b,i-1,24)&&x.close>hi(b,i-1,24),c[i-1]>lo(b,i-1,24)&&x.close<lo(b,i-1,24));add('RETEST_48','PULLBACK',c[i-1]<hi(b,i-1,48)&&x.close>hi(b,i-1,48),c[i-1]>lo(b,i-1,48)&&x.close<lo(b,i-1,48));add('TREND_DIP','PULLBACK',e20[i]>e50[i]&&rr[i]>45&&rr[i]<60&&x.close>e20[i],e20[i]<e50[i]&&rr[i]>40&&rr[i]<55&&x.close<e20[i]);add('TREND_RECLAIM','PULLBACK',e20[i]>e50[i]&&x.low<e50[i]&&x.close>e20[i],e20[i]<e50[i]&&x.high>e50[i]&&x.close<e20[i]);
// 10 candle
const prev=b[i-1],body=Math.abs(x.close-x.open),range=Math.max(1e-9,x.high-x.low),pb=Math.abs(prev.close-prev.open);add('ENGULF','CANDLE',x.close>x.open&&prev.close<prev.open&&x.close>=prev.open&&x.open<=prev.close,x.close<x.open&&prev.close>prev.open&&x.open>=prev.close&&x.close<=prev.open);add('PINBAR','CANDLE',(x.open-x.low)>2*body&&(x.high-x.close)<body,(x.high-x.open)>2*body&&(x.close-x.low)<body);add('STRONG_BODY','CANDLE',x.close>x.open&&body/range>.7,x.close<x.open&&body/range>.7);add('OUTSIDE','CANDLE',x.high>prev.high&&x.low<prev.low&&x.close>x.open,x.high>prev.high&&x.low<prev.low&&x.close<x.open);add('INSIDE_BREAK','CANDLE',b[i-2].high>prev.high&&b[i-2].low<prev.low&&x.close>prev.high,b[i-2].high>prev.high&&b[i-2].low<prev.low&&x.close<prev.low);add('2BAR_REV','CANDLE',prev.close<prev.open&&x.close>x.open&&body>pb,prev.close>prev.open&&x.close<x.open&&body>pb);add('3BAR_MOM','CANDLE',c[i]>c[i-1]&&c[i-1]>c[i-2]&&c[i-2]>c[i-3],c[i]<c[i-1]&&c[i-1]<c[i-2]&&c[i-2]<c[i-3]);add('CLOSE_LOCATION','CANDLE',(x.close-x.low)/range>.85,(x.close-x.low)/range<.15);add('WICK_REJECT','CANDLE',(Math.min(x.open,x.close)-x.low)/range>.55,(x.high-Math.max(x.open,x.close))/range>.55);add('GAPLIKE','CANDLE',x.open>prev.close&&x.close>prev.high,x.open<prev.close&&x.close<prev.low);
// 10 mean reversion
for(const [n,t] of [[1,30],[2,35],[3,40]] as any[])add(`RSI_REV_${n}`,'MEANREV',rr[i]<t,rr[i]>100-t);for(const [n,k] of [[4,1],[5,1.5],[6,2],[7,2.5]] as any[])add(`EMADEV_${n}`,'MEANREV',x.close<e20[i]-k*aa[i],x.close>e20[i]+k*aa[i]);add('RANGE_FADE','MEANREV',x.low<lo(b,i,24)&&x.close>lo(b,i,24),x.high>hi(b,i,24)&&x.close<hi(b,i,24));add('RSI_PRICE_DIV_PROXY','MEANREV',rr[i]>rr[i-6]&&c[i]<c[i-6],rr[i]<rr[i-6]&&c[i]>c[i-6]);add('EMA200_MAGNET','MEANREV',x.close<e200[i]-2*aa[i],x.close>e200[i]+2*aa[i]);
// 10 volume/wyckoff proxies
const vm=sma(v,48,i);add('VOL_TREND','VOLUME',x.volume>vm*1.5&&x.close>x.open,x.volume>vm*1.5&&x.close<x.open);add('SPRING','VOLUME',x.low<lo(b,i,48)&&x.close>lo(b,i,48)&&x.volume>vm*1.2,x.high>hi(b,i,48)&&x.close<hi(b,i,48)&&x.volume>vm*1.2);add('STOPPING_VOL','VOLUME',x.volume>vm*2&&body/range<.35&&(x.close-x.low)/range>.6,x.volume>vm*2&&body/range<.35&&(x.close-x.low)/range<.4);add('EFFORT_RESULT','VOLUME',x.volume>vm*1.8&&range<aa[i]*.8&&x.close>x.open,x.volume>vm*1.8&&range<aa[i]*.8&&x.close<x.open);add('LOWVOL_TEST','VOLUME',x.volume<vm*.6&&e20[i]>e50[i]&&x.close>x.open,x.volume<vm*.6&&e20[i]<e50[i]&&x.close<x.open);add('VOL_BREAK_RETEST','VOLUME',x.volume>vm&&x.close>hi(b,i,24),x.volume>vm&&x.close<lo(b,i,24));add('CLIMAX_REJECT','VOLUME',x.volume>vm*2.5&&(x.close-x.low)/range>.75,x.volume>vm*2.5&&(x.close-x.low)/range<.25);add('ABSORB_PROXY','VOLUME',x.volume>vm*1.5&&range<aa[i]&&x.close>e20[i],x.volume>vm*1.5&&range<aa[i]&&x.close<e20[i]);add('REACCUM_PROXY','VOLUME',e20[i]>e50[i]&&x.volume<vm&&range<aa[i]&&x.close>e20[i],e20[i]<e50[i]&&x.volume<vm&&range<aa[i]&&x.close<e20[i]);add('VOL_EXPANSION','VOLUME',x.volume>vm*1.7&&range>aa[i]*1.2&&x.close>x.open,x.volume>vm*1.7&&range>aa[i]*1.2&&x.close<x.open);
// 10 structure/regime
add('HHHL','STRUCTURE',hi(b,i,12)>hi(b,i-12,12)&&lo(b,i,12)>lo(b,i-12,12),hi(b,i,12)<hi(b,i-12,12)&&lo(b,i,12)<lo(b,i-12,12));add('BREAK_SWING','STRUCTURE',x.close>hi(b,i,12),x.close<lo(b,i,12));add('4H_TREND','STRUCTURE',e4_20[j4]>e4_50[j4]&&slope(c4,j4,3)>0,e4_20[j4]<e4_50[j4]&&slope(c4,j4,3)<0);add('4H_MOM','STRUCTURE',slope(c4,j4,2)>.3,slope(c4,j4,2)<-.3);add('VOLATILE_TREND','STRUCTURE',aa[i]/x.close*100>.15&&e20[i]>e50[i],aa[i]/x.close*100>.15&&e20[i]<e50[i]);add('CALM_BREAK','STRUCTURE',aa[i]/x.close*100<.2&&x.close>hi(b,i,24),aa[i]/x.close*100<.2&&x.close<lo(b,i,24));add('ABOVE_DAILY_PROXY','STRUCTURE',x.close>sma(c,48,i),x.close<sma(c,48,i));add('WEEK_PROXY','STRUCTURE',x.close>sma(c,240,i),x.close<sma(c,240,i));add('RANGE_EDGE','STRUCTURE',x.close>(hi(b,i,48)+lo(b,i,48))/2,x.close<(hi(b,i,48)+lo(b,i,48))/2);add('TREND_CONSENSUS','STRUCTURE',e9[i]>e20[i]&&e20[i]>e50[i]&&e4_20[j4]>e4_50[j4],e9[i]<e20[i]&&e20[i]<e50[i]&&e4_20[j4]<e4_50[j4]);
return res.slice(0,100)}
function test(b:Bar[],tf4:Bar[],start:number,end:number,minVotes=5,minFamilies=3){const a=atr(b,14);let eq=100,pk=100,dd=0,gp=0,gl=0,w=0,n=0,sv=0;for(let i=Math.max(start,260);i<end-20;i++){const j4=Math.max(0,Math.floor((b[i].time-tf4[0].time)/(4*3600000)));const vs=votes(b,i,tf4,Math.min(j4,tf4.length-1)),bu=vs.filter(x=>x.side==='BUY'),se=vs.filter(x=>x.side==='SELL');const side=bu.length>=minVotes&&new Set(bu.map(x=>x.family)).size>=minFamilies&&bu.length>se.length?'BUY':se.length>=minVotes&&new Set(se.map(x=>x.family)).size>=minFamilies&&se.length>bu.length?'SELL':null;if(!side)continue;const vv=side==='BUY'?bu:se,entry=b[i+1].open,risk=1.2*a[i],tp=side==='BUY'?entry+2*risk:entry-2*risk,sl=side==='BUY'?entry-risk:entry+risk;let exit=b[Math.min(end-1,i+13)].close;for(let j=i+1;j<=Math.min(end-1,i+13);j++){if(side==='BUY'){if(b[j].low<=sl){exit=sl;break}if(b[j].high>=tp){exit=tp;break}}else{if(b[j].high>=sl){exit=sl;break}if(b[j].low<=tp){exit=tp;break}}}const gross=side==='BUY'?(exit-entry)/entry*100:(entry-exit)/entry*100,ret=(gross-COST)*EXPOSURE;eq*=1+ret/100;pk=Math.max(pk,eq);dd=Math.max(dd,(pk-eq)/pk*100);if(ret>0){w++;gp+=ret}else gl+=Math.abs(ret);n++;sv+=vv.length;i+=2;}const days=(b[end-1].time-b[start].time)/DAY;return{trades:n,wins:w,winRate:n?w/n*100:0,profitFactor:gl?gp/gl:gp?99:0,accountReturnPct:eq-100,maxDrawdownPct:dd,final50:50*eq/100,avgVotes:n?sv/n:0,tradesPerDay:n/Math.max(1,days)} as Stats}
async function main(){const end=Math.floor((Date.now()-2*DAY)/DAY)*DAY,start=end-DAYS*DAY,dir=await mkdtemp(path.join(os.tmpdir(),'xau100-')),m1:Bar[]=[];for(let t=start;t<end;t+=DAY){const d=new Date(t).toISOString().slice(0,10),r=await day(d,dir);if(r.length)console.log('DAY',d,r.length);m1.push(...r)}const m30=agg(m1,30*60000),h4=agg(m1,4*3600000);console.log('BARS',JSON.stringify({m30:m30.length,h4:h4.length}));const n=m30.length,tr=Math.floor(n*.5),va=Math.floor(n*.75);for(const mv of [5,6,7,8,10,12,15]){const A=test(m30,h4,0,tr,mv,3),B=test(m30,h4,tr,va,mv,3),C=test(m30,h4,va,n,mv,3);console.log('RESULT',JSON.stringify({minVotes:mv,minFamilies:3,train:A,validation:B,test:C,survived:A.accountReturnPct>0&&A.profitFactor>1&&B.accountReturnPct>0&&B.profitFactor>1&&C.accountReturnPct>0&&C.profitFactor>1&&C.trades>=5}))}}
main().catch(e=>{console.error(e);process.exit(1)});